// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/faster_rcnn.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "object_detection/protos/anchor_generator.pb.h"
#include "object_detection/protos/box_predictor.pb.h"
#include "object_detection/protos/hyperparams.pb.h"
#include "object_detection/protos/image_resizer.pb.h"
#include "object_detection/protos/losses.pb.h"
#include "object_detection/protos/post_processing.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto;
namespace object_detection {
namespace protos {
class FasterRcnn;
class FasterRcnnDefaultTypeInternal;
extern FasterRcnnDefaultTypeInternal _FasterRcnn_default_instance_;
class FasterRcnnFeatureExtractor;
class FasterRcnnFeatureExtractorDefaultTypeInternal;
extern FasterRcnnFeatureExtractorDefaultTypeInternal _FasterRcnnFeatureExtractor_default_instance_;
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> ::object_detection::protos::FasterRcnn* Arena::CreateMaybeMessage<::object_detection::protos::FasterRcnn>(Arena*);
template<> ::object_detection::protos::FasterRcnnFeatureExtractor* Arena::CreateMaybeMessage<::object_detection::protos::FasterRcnnFeatureExtractor>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace object_detection {
namespace protos {

// ===================================================================

class FasterRcnn :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.FasterRcnn) */ {
 public:
  FasterRcnn();
  virtual ~FasterRcnn();

  FasterRcnn(const FasterRcnn& from);
  FasterRcnn(FasterRcnn&& from) noexcept
    : FasterRcnn() {
    *this = ::std::move(from);
  }

  inline FasterRcnn& operator=(const FasterRcnn& from) {
    CopyFrom(from);
    return *this;
  }
  inline FasterRcnn& operator=(FasterRcnn&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FasterRcnn& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FasterRcnn* internal_default_instance() {
    return reinterpret_cast<const FasterRcnn*>(
               &_FasterRcnn_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FasterRcnn& a, FasterRcnn& b) {
    a.Swap(&b);
  }
  inline void Swap(FasterRcnn* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FasterRcnn* New() const final {
    return CreateMaybeMessage<FasterRcnn>(nullptr);
  }

  FasterRcnn* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FasterRcnn>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FasterRcnn& from);
  void MergeFrom(const FasterRcnn& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FasterRcnn* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.FasterRcnn";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageResizerFieldNumber = 4,
    kFeatureExtractorFieldNumber = 5,
    kFirstStageAnchorGeneratorFieldNumber = 6,
    kFirstStageBoxPredictorConvHyperparamsFieldNumber = 8,
    kSecondStageBoxPredictorFieldNumber = 21,
    kSecondStagePostProcessingFieldNumber = 24,
    kHardExampleMinerFieldNumber = 28,
    kSecondStageClassificationLossFieldNumber = 29,
    kNumClassesFieldNumber = 3,
    kFirstStageNmsScoreThresholdFieldNumber = 13,
    kInitialCropSizeFieldNumber = 18,
    kMaxpoolKernelSizeFieldNumber = 19,
    kMaxpoolStrideFieldNumber = 20,
    kInplaceBatchnormUpdateFieldNumber = 30,
    kUseMatmulCropAndResizeFieldNumber = 31,
    kClipAnchorsToImageFieldNumber = 32,
    kUseMatmulGatherInMatcherFieldNumber = 33,
    kUseStaticBalancedLabelSamplerFieldNumber = 34,
    kUseStaticShapesFieldNumber = 35,
    kUseStaticShapesForEvalFieldNumber = 37,
    kNumberOfStagesFieldNumber = 1,
    kFirstStageAtrousRateFieldNumber = 7,
    kFirstStageBoxPredictorKernelSizeFieldNumber = 9,
    kFirstStageBoxPredictorDepthFieldNumber = 10,
    kFirstStageMinibatchSizeFieldNumber = 11,
    kFirstStagePositiveBalanceFractionFieldNumber = 12,
    kFirstStageNmsIouThresholdFieldNumber = 14,
    kFirstStageMaxProposalsFieldNumber = 15,
    kFirstStageLocalizationLossWeightFieldNumber = 16,
    kFirstStageObjectnessLossWeightFieldNumber = 17,
    kSecondStageBatchSizeFieldNumber = 22,
    kSecondStageBalanceFractionFieldNumber = 23,
    kSecondStageLocalizationLossWeightFieldNumber = 25,
    kSecondStageClassificationLossWeightFieldNumber = 26,
    kSecondStageMaskPredictionLossWeightFieldNumber = 27,
    kResizeMasksFieldNumber = 36,
  };
  // optional .object_detection.protos.ImageResizer image_resizer = 4;
  bool has_image_resizer() const;
  void clear_image_resizer();
  const ::object_detection::protos::ImageResizer& image_resizer() const;
  ::object_detection::protos::ImageResizer* release_image_resizer();
  ::object_detection::protos::ImageResizer* mutable_image_resizer();
  void set_allocated_image_resizer(::object_detection::protos::ImageResizer* image_resizer);

  // optional .object_detection.protos.FasterRcnnFeatureExtractor feature_extractor = 5;
  bool has_feature_extractor() const;
  void clear_feature_extractor();
  const ::object_detection::protos::FasterRcnnFeatureExtractor& feature_extractor() const;
  ::object_detection::protos::FasterRcnnFeatureExtractor* release_feature_extractor();
  ::object_detection::protos::FasterRcnnFeatureExtractor* mutable_feature_extractor();
  void set_allocated_feature_extractor(::object_detection::protos::FasterRcnnFeatureExtractor* feature_extractor);

  // optional .object_detection.protos.AnchorGenerator first_stage_anchor_generator = 6;
  bool has_first_stage_anchor_generator() const;
  void clear_first_stage_anchor_generator();
  const ::object_detection::protos::AnchorGenerator& first_stage_anchor_generator() const;
  ::object_detection::protos::AnchorGenerator* release_first_stage_anchor_generator();
  ::object_detection::protos::AnchorGenerator* mutable_first_stage_anchor_generator();
  void set_allocated_first_stage_anchor_generator(::object_detection::protos::AnchorGenerator* first_stage_anchor_generator);

  // optional .object_detection.protos.Hyperparams first_stage_box_predictor_conv_hyperparams = 8;
  bool has_first_stage_box_predictor_conv_hyperparams() const;
  void clear_first_stage_box_predictor_conv_hyperparams();
  const ::object_detection::protos::Hyperparams& first_stage_box_predictor_conv_hyperparams() const;
  ::object_detection::protos::Hyperparams* release_first_stage_box_predictor_conv_hyperparams();
  ::object_detection::protos::Hyperparams* mutable_first_stage_box_predictor_conv_hyperparams();
  void set_allocated_first_stage_box_predictor_conv_hyperparams(::object_detection::protos::Hyperparams* first_stage_box_predictor_conv_hyperparams);

  // optional .object_detection.protos.BoxPredictor second_stage_box_predictor = 21;
  bool has_second_stage_box_predictor() const;
  void clear_second_stage_box_predictor();
  const ::object_detection::protos::BoxPredictor& second_stage_box_predictor() const;
  ::object_detection::protos::BoxPredictor* release_second_stage_box_predictor();
  ::object_detection::protos::BoxPredictor* mutable_second_stage_box_predictor();
  void set_allocated_second_stage_box_predictor(::object_detection::protos::BoxPredictor* second_stage_box_predictor);

  // optional .object_detection.protos.PostProcessing second_stage_post_processing = 24;
  bool has_second_stage_post_processing() const;
  void clear_second_stage_post_processing();
  const ::object_detection::protos::PostProcessing& second_stage_post_processing() const;
  ::object_detection::protos::PostProcessing* release_second_stage_post_processing();
  ::object_detection::protos::PostProcessing* mutable_second_stage_post_processing();
  void set_allocated_second_stage_post_processing(::object_detection::protos::PostProcessing* second_stage_post_processing);

  // optional .object_detection.protos.HardExampleMiner hard_example_miner = 28;
  bool has_hard_example_miner() const;
  void clear_hard_example_miner();
  const ::object_detection::protos::HardExampleMiner& hard_example_miner() const;
  ::object_detection::protos::HardExampleMiner* release_hard_example_miner();
  ::object_detection::protos::HardExampleMiner* mutable_hard_example_miner();
  void set_allocated_hard_example_miner(::object_detection::protos::HardExampleMiner* hard_example_miner);

  // optional .object_detection.protos.ClassificationLoss second_stage_classification_loss = 29;
  bool has_second_stage_classification_loss() const;
  void clear_second_stage_classification_loss();
  const ::object_detection::protos::ClassificationLoss& second_stage_classification_loss() const;
  ::object_detection::protos::ClassificationLoss* release_second_stage_classification_loss();
  ::object_detection::protos::ClassificationLoss* mutable_second_stage_classification_loss();
  void set_allocated_second_stage_classification_loss(::object_detection::protos::ClassificationLoss* second_stage_classification_loss);

  // optional int32 num_classes = 3;
  bool has_num_classes() const;
  void clear_num_classes();
  ::PROTOBUF_NAMESPACE_ID::int32 num_classes() const;
  void set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float first_stage_nms_score_threshold = 13 [default = 0];
  bool has_first_stage_nms_score_threshold() const;
  void clear_first_stage_nms_score_threshold();
  float first_stage_nms_score_threshold() const;
  void set_first_stage_nms_score_threshold(float value);

  // optional int32 initial_crop_size = 18;
  bool has_initial_crop_size() const;
  void clear_initial_crop_size();
  ::PROTOBUF_NAMESPACE_ID::int32 initial_crop_size() const;
  void set_initial_crop_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 maxpool_kernel_size = 19;
  bool has_maxpool_kernel_size() const;
  void clear_maxpool_kernel_size();
  ::PROTOBUF_NAMESPACE_ID::int32 maxpool_kernel_size() const;
  void set_maxpool_kernel_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 maxpool_stride = 20;
  bool has_maxpool_stride() const;
  void clear_maxpool_stride();
  ::PROTOBUF_NAMESPACE_ID::int32 maxpool_stride() const;
  void set_maxpool_stride(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional bool inplace_batchnorm_update = 30 [default = false];
  bool has_inplace_batchnorm_update() const;
  void clear_inplace_batchnorm_update();
  bool inplace_batchnorm_update() const;
  void set_inplace_batchnorm_update(bool value);

  // optional bool use_matmul_crop_and_resize = 31 [default = false];
  bool has_use_matmul_crop_and_resize() const;
  void clear_use_matmul_crop_and_resize();
  bool use_matmul_crop_and_resize() const;
  void set_use_matmul_crop_and_resize(bool value);

  // optional bool clip_anchors_to_image = 32 [default = false];
  bool has_clip_anchors_to_image() const;
  void clear_clip_anchors_to_image();
  bool clip_anchors_to_image() const;
  void set_clip_anchors_to_image(bool value);

  // optional bool use_matmul_gather_in_matcher = 33 [default = false];
  bool has_use_matmul_gather_in_matcher() const;
  void clear_use_matmul_gather_in_matcher();
  bool use_matmul_gather_in_matcher() const;
  void set_use_matmul_gather_in_matcher(bool value);

  // optional bool use_static_balanced_label_sampler = 34 [default = false];
  bool has_use_static_balanced_label_sampler() const;
  void clear_use_static_balanced_label_sampler();
  bool use_static_balanced_label_sampler() const;
  void set_use_static_balanced_label_sampler(bool value);

  // optional bool use_static_shapes = 35 [default = false];
  bool has_use_static_shapes() const;
  void clear_use_static_shapes();
  bool use_static_shapes() const;
  void set_use_static_shapes(bool value);

  // optional bool use_static_shapes_for_eval = 37 [default = false];
  bool has_use_static_shapes_for_eval() const;
  void clear_use_static_shapes_for_eval();
  bool use_static_shapes_for_eval() const;
  void set_use_static_shapes_for_eval(bool value);

  // optional int32 number_of_stages = 1 [default = 2];
  bool has_number_of_stages() const;
  void clear_number_of_stages();
  ::PROTOBUF_NAMESPACE_ID::int32 number_of_stages() const;
  void set_number_of_stages(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 first_stage_atrous_rate = 7 [default = 1];
  bool has_first_stage_atrous_rate() const;
  void clear_first_stage_atrous_rate();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_atrous_rate() const;
  void set_first_stage_atrous_rate(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 first_stage_box_predictor_kernel_size = 9 [default = 3];
  bool has_first_stage_box_predictor_kernel_size() const;
  void clear_first_stage_box_predictor_kernel_size();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_box_predictor_kernel_size() const;
  void set_first_stage_box_predictor_kernel_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 first_stage_box_predictor_depth = 10 [default = 512];
  bool has_first_stage_box_predictor_depth() const;
  void clear_first_stage_box_predictor_depth();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_box_predictor_depth() const;
  void set_first_stage_box_predictor_depth(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 first_stage_minibatch_size = 11 [default = 256];
  bool has_first_stage_minibatch_size() const;
  void clear_first_stage_minibatch_size();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_minibatch_size() const;
  void set_first_stage_minibatch_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float first_stage_positive_balance_fraction = 12 [default = 0.5];
  bool has_first_stage_positive_balance_fraction() const;
  void clear_first_stage_positive_balance_fraction();
  float first_stage_positive_balance_fraction() const;
  void set_first_stage_positive_balance_fraction(float value);

  // optional float first_stage_nms_iou_threshold = 14 [default = 0.7];
  bool has_first_stage_nms_iou_threshold() const;
  void clear_first_stage_nms_iou_threshold();
  float first_stage_nms_iou_threshold() const;
  void set_first_stage_nms_iou_threshold(float value);

  // optional int32 first_stage_max_proposals = 15 [default = 300];
  bool has_first_stage_max_proposals() const;
  void clear_first_stage_max_proposals();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_max_proposals() const;
  void set_first_stage_max_proposals(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float first_stage_localization_loss_weight = 16 [default = 1];
  bool has_first_stage_localization_loss_weight() const;
  void clear_first_stage_localization_loss_weight();
  float first_stage_localization_loss_weight() const;
  void set_first_stage_localization_loss_weight(float value);

  // optional float first_stage_objectness_loss_weight = 17 [default = 1];
  bool has_first_stage_objectness_loss_weight() const;
  void clear_first_stage_objectness_loss_weight();
  float first_stage_objectness_loss_weight() const;
  void set_first_stage_objectness_loss_weight(float value);

  // optional int32 second_stage_batch_size = 22 [default = 64];
  bool has_second_stage_batch_size() const;
  void clear_second_stage_batch_size();
  ::PROTOBUF_NAMESPACE_ID::int32 second_stage_batch_size() const;
  void set_second_stage_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float second_stage_balance_fraction = 23 [default = 0.25];
  bool has_second_stage_balance_fraction() const;
  void clear_second_stage_balance_fraction();
  float second_stage_balance_fraction() const;
  void set_second_stage_balance_fraction(float value);

  // optional float second_stage_localization_loss_weight = 25 [default = 1];
  bool has_second_stage_localization_loss_weight() const;
  void clear_second_stage_localization_loss_weight();
  float second_stage_localization_loss_weight() const;
  void set_second_stage_localization_loss_weight(float value);

  // optional float second_stage_classification_loss_weight = 26 [default = 1];
  bool has_second_stage_classification_loss_weight() const;
  void clear_second_stage_classification_loss_weight();
  float second_stage_classification_loss_weight() const;
  void set_second_stage_classification_loss_weight(float value);

  // optional float second_stage_mask_prediction_loss_weight = 27 [default = 1];
  bool has_second_stage_mask_prediction_loss_weight() const;
  void clear_second_stage_mask_prediction_loss_weight();
  float second_stage_mask_prediction_loss_weight() const;
  void set_second_stage_mask_prediction_loss_weight(float value);

  // optional bool resize_masks = 36 [default = true];
  bool has_resize_masks() const;
  void clear_resize_masks();
  bool resize_masks() const;
  void set_resize_masks(bool value);

  // @@protoc_insertion_point(class_scope:object_detection.protos.FasterRcnn)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<2> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::object_detection::protos::ImageResizer* image_resizer_;
  ::object_detection::protos::FasterRcnnFeatureExtractor* feature_extractor_;
  ::object_detection::protos::AnchorGenerator* first_stage_anchor_generator_;
  ::object_detection::protos::Hyperparams* first_stage_box_predictor_conv_hyperparams_;
  ::object_detection::protos::BoxPredictor* second_stage_box_predictor_;
  ::object_detection::protos::PostProcessing* second_stage_post_processing_;
  ::object_detection::protos::HardExampleMiner* hard_example_miner_;
  ::object_detection::protos::ClassificationLoss* second_stage_classification_loss_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_classes_;
  float first_stage_nms_score_threshold_;
  ::PROTOBUF_NAMESPACE_ID::int32 initial_crop_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 maxpool_kernel_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 maxpool_stride_;
  bool inplace_batchnorm_update_;
  bool use_matmul_crop_and_resize_;
  bool clip_anchors_to_image_;
  bool use_matmul_gather_in_matcher_;
  bool use_static_balanced_label_sampler_;
  bool use_static_shapes_;
  bool use_static_shapes_for_eval_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_of_stages_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_atrous_rate_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_box_predictor_kernel_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_box_predictor_depth_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_minibatch_size_;
  float first_stage_positive_balance_fraction_;
  float first_stage_nms_iou_threshold_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_max_proposals_;
  float first_stage_localization_loss_weight_;
  float first_stage_objectness_loss_weight_;
  ::PROTOBUF_NAMESPACE_ID::int32 second_stage_batch_size_;
  float second_stage_balance_fraction_;
  float second_stage_localization_loss_weight_;
  float second_stage_classification_loss_weight_;
  float second_stage_mask_prediction_loss_weight_;
  bool resize_masks_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto;
};
// -------------------------------------------------------------------

class FasterRcnnFeatureExtractor :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.FasterRcnnFeatureExtractor) */ {
 public:
  FasterRcnnFeatureExtractor();
  virtual ~FasterRcnnFeatureExtractor();

  FasterRcnnFeatureExtractor(const FasterRcnnFeatureExtractor& from);
  FasterRcnnFeatureExtractor(FasterRcnnFeatureExtractor&& from) noexcept
    : FasterRcnnFeatureExtractor() {
    *this = ::std::move(from);
  }

  inline FasterRcnnFeatureExtractor& operator=(const FasterRcnnFeatureExtractor& from) {
    CopyFrom(from);
    return *this;
  }
  inline FasterRcnnFeatureExtractor& operator=(FasterRcnnFeatureExtractor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FasterRcnnFeatureExtractor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FasterRcnnFeatureExtractor* internal_default_instance() {
    return reinterpret_cast<const FasterRcnnFeatureExtractor*>(
               &_FasterRcnnFeatureExtractor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FasterRcnnFeatureExtractor& a, FasterRcnnFeatureExtractor& b) {
    a.Swap(&b);
  }
  inline void Swap(FasterRcnnFeatureExtractor* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FasterRcnnFeatureExtractor* New() const final {
    return CreateMaybeMessage<FasterRcnnFeatureExtractor>(nullptr);
  }

  FasterRcnnFeatureExtractor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FasterRcnnFeatureExtractor>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FasterRcnnFeatureExtractor& from);
  void MergeFrom(const FasterRcnnFeatureExtractor& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FasterRcnnFeatureExtractor* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.FasterRcnnFeatureExtractor";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kBatchNormTrainableFieldNumber = 3,
    kFirstStageFeaturesStrideFieldNumber = 2,
  };
  // optional string type = 1;
  bool has_type() const;
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);

  // optional bool batch_norm_trainable = 3 [default = false];
  bool has_batch_norm_trainable() const;
  void clear_batch_norm_trainable();
  bool batch_norm_trainable() const;
  void set_batch_norm_trainable(bool value);

  // optional int32 first_stage_features_stride = 2 [default = 16];
  bool has_first_stage_features_stride() const;
  void clear_first_stage_features_stride();
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_features_stride() const;
  void set_first_stage_features_stride(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:object_detection.protos.FasterRcnnFeatureExtractor)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  bool batch_norm_trainable_;
  ::PROTOBUF_NAMESPACE_ID::int32 first_stage_features_stride_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FasterRcnn

// optional int32 number_of_stages = 1 [default = 2];
inline bool FasterRcnn::has_number_of_stages() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void FasterRcnn::clear_number_of_stages() {
  number_of_stages_ = 2;
  _has_bits_[0] &= ~0x00100000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::number_of_stages() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.number_of_stages)
  return number_of_stages_;
}
inline void FasterRcnn::set_number_of_stages(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00100000u;
  number_of_stages_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.number_of_stages)
}

// optional int32 num_classes = 3;
inline bool FasterRcnn::has_num_classes() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void FasterRcnn::clear_num_classes() {
  num_classes_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::num_classes() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.num_classes)
  return num_classes_;
}
inline void FasterRcnn::set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  num_classes_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.num_classes)
}

// optional .object_detection.protos.ImageResizer image_resizer = 4;
inline bool FasterRcnn::has_image_resizer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::object_detection::protos::ImageResizer& FasterRcnn::image_resizer() const {
  const ::object_detection::protos::ImageResizer* p = image_resizer_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.image_resizer)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::ImageResizer*>(
      &::object_detection::protos::_ImageResizer_default_instance_);
}
inline ::object_detection::protos::ImageResizer* FasterRcnn::release_image_resizer() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.image_resizer)
  _has_bits_[0] &= ~0x00000001u;
  ::object_detection::protos::ImageResizer* temp = image_resizer_;
  image_resizer_ = nullptr;
  return temp;
}
inline ::object_detection::protos::ImageResizer* FasterRcnn::mutable_image_resizer() {
  _has_bits_[0] |= 0x00000001u;
  if (image_resizer_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::ImageResizer>(GetArenaNoVirtual());
    image_resizer_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.image_resizer)
  return image_resizer_;
}
inline void FasterRcnn::set_allocated_image_resizer(::object_detection::protos::ImageResizer* image_resizer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(image_resizer_);
  }
  if (image_resizer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      image_resizer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, image_resizer, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  image_resizer_ = image_resizer;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.image_resizer)
}

// optional .object_detection.protos.FasterRcnnFeatureExtractor feature_extractor = 5;
inline bool FasterRcnn::has_feature_extractor() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FasterRcnn::clear_feature_extractor() {
  if (feature_extractor_ != nullptr) feature_extractor_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::object_detection::protos::FasterRcnnFeatureExtractor& FasterRcnn::feature_extractor() const {
  const ::object_detection::protos::FasterRcnnFeatureExtractor* p = feature_extractor_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.feature_extractor)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::FasterRcnnFeatureExtractor*>(
      &::object_detection::protos::_FasterRcnnFeatureExtractor_default_instance_);
}
inline ::object_detection::protos::FasterRcnnFeatureExtractor* FasterRcnn::release_feature_extractor() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.feature_extractor)
  _has_bits_[0] &= ~0x00000002u;
  ::object_detection::protos::FasterRcnnFeatureExtractor* temp = feature_extractor_;
  feature_extractor_ = nullptr;
  return temp;
}
inline ::object_detection::protos::FasterRcnnFeatureExtractor* FasterRcnn::mutable_feature_extractor() {
  _has_bits_[0] |= 0x00000002u;
  if (feature_extractor_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::FasterRcnnFeatureExtractor>(GetArenaNoVirtual());
    feature_extractor_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.feature_extractor)
  return feature_extractor_;
}
inline void FasterRcnn::set_allocated_feature_extractor(::object_detection::protos::FasterRcnnFeatureExtractor* feature_extractor) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete feature_extractor_;
  }
  if (feature_extractor) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      feature_extractor = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, feature_extractor, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  feature_extractor_ = feature_extractor;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.feature_extractor)
}

// optional .object_detection.protos.AnchorGenerator first_stage_anchor_generator = 6;
inline bool FasterRcnn::has_first_stage_anchor_generator() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::object_detection::protos::AnchorGenerator& FasterRcnn::first_stage_anchor_generator() const {
  const ::object_detection::protos::AnchorGenerator* p = first_stage_anchor_generator_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_anchor_generator)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::AnchorGenerator*>(
      &::object_detection::protos::_AnchorGenerator_default_instance_);
}
inline ::object_detection::protos::AnchorGenerator* FasterRcnn::release_first_stage_anchor_generator() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.first_stage_anchor_generator)
  _has_bits_[0] &= ~0x00000004u;
  ::object_detection::protos::AnchorGenerator* temp = first_stage_anchor_generator_;
  first_stage_anchor_generator_ = nullptr;
  return temp;
}
inline ::object_detection::protos::AnchorGenerator* FasterRcnn::mutable_first_stage_anchor_generator() {
  _has_bits_[0] |= 0x00000004u;
  if (first_stage_anchor_generator_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::AnchorGenerator>(GetArenaNoVirtual());
    first_stage_anchor_generator_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.first_stage_anchor_generator)
  return first_stage_anchor_generator_;
}
inline void FasterRcnn::set_allocated_first_stage_anchor_generator(::object_detection::protos::AnchorGenerator* first_stage_anchor_generator) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(first_stage_anchor_generator_);
  }
  if (first_stage_anchor_generator) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      first_stage_anchor_generator = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, first_stage_anchor_generator, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  first_stage_anchor_generator_ = first_stage_anchor_generator;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.first_stage_anchor_generator)
}

// optional int32 first_stage_atrous_rate = 7 [default = 1];
inline bool FasterRcnn::has_first_stage_atrous_rate() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void FasterRcnn::clear_first_stage_atrous_rate() {
  first_stage_atrous_rate_ = 1;
  _has_bits_[0] &= ~0x00200000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::first_stage_atrous_rate() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_atrous_rate)
  return first_stage_atrous_rate_;
}
inline void FasterRcnn::set_first_stage_atrous_rate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00200000u;
  first_stage_atrous_rate_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_atrous_rate)
}

// optional .object_detection.protos.Hyperparams first_stage_box_predictor_conv_hyperparams = 8;
inline bool FasterRcnn::has_first_stage_box_predictor_conv_hyperparams() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline const ::object_detection::protos::Hyperparams& FasterRcnn::first_stage_box_predictor_conv_hyperparams() const {
  const ::object_detection::protos::Hyperparams* p = first_stage_box_predictor_conv_hyperparams_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_box_predictor_conv_hyperparams)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::Hyperparams*>(
      &::object_detection::protos::_Hyperparams_default_instance_);
}
inline ::object_detection::protos::Hyperparams* FasterRcnn::release_first_stage_box_predictor_conv_hyperparams() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.first_stage_box_predictor_conv_hyperparams)
  _has_bits_[0] &= ~0x00000008u;
  ::object_detection::protos::Hyperparams* temp = first_stage_box_predictor_conv_hyperparams_;
  first_stage_box_predictor_conv_hyperparams_ = nullptr;
  return temp;
}
inline ::object_detection::protos::Hyperparams* FasterRcnn::mutable_first_stage_box_predictor_conv_hyperparams() {
  _has_bits_[0] |= 0x00000008u;
  if (first_stage_box_predictor_conv_hyperparams_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::Hyperparams>(GetArenaNoVirtual());
    first_stage_box_predictor_conv_hyperparams_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.first_stage_box_predictor_conv_hyperparams)
  return first_stage_box_predictor_conv_hyperparams_;
}
inline void FasterRcnn::set_allocated_first_stage_box_predictor_conv_hyperparams(::object_detection::protos::Hyperparams* first_stage_box_predictor_conv_hyperparams) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(first_stage_box_predictor_conv_hyperparams_);
  }
  if (first_stage_box_predictor_conv_hyperparams) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      first_stage_box_predictor_conv_hyperparams = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, first_stage_box_predictor_conv_hyperparams, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  first_stage_box_predictor_conv_hyperparams_ = first_stage_box_predictor_conv_hyperparams;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.first_stage_box_predictor_conv_hyperparams)
}

// optional int32 first_stage_box_predictor_kernel_size = 9 [default = 3];
inline bool FasterRcnn::has_first_stage_box_predictor_kernel_size() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void FasterRcnn::clear_first_stage_box_predictor_kernel_size() {
  first_stage_box_predictor_kernel_size_ = 3;
  _has_bits_[0] &= ~0x00400000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::first_stage_box_predictor_kernel_size() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_box_predictor_kernel_size)
  return first_stage_box_predictor_kernel_size_;
}
inline void FasterRcnn::set_first_stage_box_predictor_kernel_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00400000u;
  first_stage_box_predictor_kernel_size_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_box_predictor_kernel_size)
}

// optional int32 first_stage_box_predictor_depth = 10 [default = 512];
inline bool FasterRcnn::has_first_stage_box_predictor_depth() const {
  return (_has_bits_[0] & 0x00800000u) != 0;
}
inline void FasterRcnn::clear_first_stage_box_predictor_depth() {
  first_stage_box_predictor_depth_ = 512;
  _has_bits_[0] &= ~0x00800000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::first_stage_box_predictor_depth() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_box_predictor_depth)
  return first_stage_box_predictor_depth_;
}
inline void FasterRcnn::set_first_stage_box_predictor_depth(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00800000u;
  first_stage_box_predictor_depth_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_box_predictor_depth)
}

// optional int32 first_stage_minibatch_size = 11 [default = 256];
inline bool FasterRcnn::has_first_stage_minibatch_size() const {
  return (_has_bits_[0] & 0x01000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_minibatch_size() {
  first_stage_minibatch_size_ = 256;
  _has_bits_[0] &= ~0x01000000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::first_stage_minibatch_size() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_minibatch_size)
  return first_stage_minibatch_size_;
}
inline void FasterRcnn::set_first_stage_minibatch_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x01000000u;
  first_stage_minibatch_size_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_minibatch_size)
}

// optional float first_stage_positive_balance_fraction = 12 [default = 0.5];
inline bool FasterRcnn::has_first_stage_positive_balance_fraction() const {
  return (_has_bits_[0] & 0x02000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_positive_balance_fraction() {
  first_stage_positive_balance_fraction_ = 0.5f;
  _has_bits_[0] &= ~0x02000000u;
}
inline float FasterRcnn::first_stage_positive_balance_fraction() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_positive_balance_fraction)
  return first_stage_positive_balance_fraction_;
}
inline void FasterRcnn::set_first_stage_positive_balance_fraction(float value) {
  _has_bits_[0] |= 0x02000000u;
  first_stage_positive_balance_fraction_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_positive_balance_fraction)
}

// optional float first_stage_nms_score_threshold = 13 [default = 0];
inline bool FasterRcnn::has_first_stage_nms_score_threshold() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void FasterRcnn::clear_first_stage_nms_score_threshold() {
  first_stage_nms_score_threshold_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline float FasterRcnn::first_stage_nms_score_threshold() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_nms_score_threshold)
  return first_stage_nms_score_threshold_;
}
inline void FasterRcnn::set_first_stage_nms_score_threshold(float value) {
  _has_bits_[0] |= 0x00000200u;
  first_stage_nms_score_threshold_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_nms_score_threshold)
}

// optional float first_stage_nms_iou_threshold = 14 [default = 0.7];
inline bool FasterRcnn::has_first_stage_nms_iou_threshold() const {
  return (_has_bits_[0] & 0x04000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_nms_iou_threshold() {
  first_stage_nms_iou_threshold_ = 0.7f;
  _has_bits_[0] &= ~0x04000000u;
}
inline float FasterRcnn::first_stage_nms_iou_threshold() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_nms_iou_threshold)
  return first_stage_nms_iou_threshold_;
}
inline void FasterRcnn::set_first_stage_nms_iou_threshold(float value) {
  _has_bits_[0] |= 0x04000000u;
  first_stage_nms_iou_threshold_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_nms_iou_threshold)
}

// optional int32 first_stage_max_proposals = 15 [default = 300];
inline bool FasterRcnn::has_first_stage_max_proposals() const {
  return (_has_bits_[0] & 0x08000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_max_proposals() {
  first_stage_max_proposals_ = 300;
  _has_bits_[0] &= ~0x08000000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::first_stage_max_proposals() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_max_proposals)
  return first_stage_max_proposals_;
}
inline void FasterRcnn::set_first_stage_max_proposals(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x08000000u;
  first_stage_max_proposals_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_max_proposals)
}

// optional float first_stage_localization_loss_weight = 16 [default = 1];
inline bool FasterRcnn::has_first_stage_localization_loss_weight() const {
  return (_has_bits_[0] & 0x10000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_localization_loss_weight() {
  first_stage_localization_loss_weight_ = 1;
  _has_bits_[0] &= ~0x10000000u;
}
inline float FasterRcnn::first_stage_localization_loss_weight() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_localization_loss_weight)
  return first_stage_localization_loss_weight_;
}
inline void FasterRcnn::set_first_stage_localization_loss_weight(float value) {
  _has_bits_[0] |= 0x10000000u;
  first_stage_localization_loss_weight_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_localization_loss_weight)
}

// optional float first_stage_objectness_loss_weight = 17 [default = 1];
inline bool FasterRcnn::has_first_stage_objectness_loss_weight() const {
  return (_has_bits_[0] & 0x20000000u) != 0;
}
inline void FasterRcnn::clear_first_stage_objectness_loss_weight() {
  first_stage_objectness_loss_weight_ = 1;
  _has_bits_[0] &= ~0x20000000u;
}
inline float FasterRcnn::first_stage_objectness_loss_weight() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.first_stage_objectness_loss_weight)
  return first_stage_objectness_loss_weight_;
}
inline void FasterRcnn::set_first_stage_objectness_loss_weight(float value) {
  _has_bits_[0] |= 0x20000000u;
  first_stage_objectness_loss_weight_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.first_stage_objectness_loss_weight)
}

// optional int32 initial_crop_size = 18;
inline bool FasterRcnn::has_initial_crop_size() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void FasterRcnn::clear_initial_crop_size() {
  initial_crop_size_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::initial_crop_size() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.initial_crop_size)
  return initial_crop_size_;
}
inline void FasterRcnn::set_initial_crop_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000400u;
  initial_crop_size_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.initial_crop_size)
}

// optional int32 maxpool_kernel_size = 19;
inline bool FasterRcnn::has_maxpool_kernel_size() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void FasterRcnn::clear_maxpool_kernel_size() {
  maxpool_kernel_size_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::maxpool_kernel_size() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.maxpool_kernel_size)
  return maxpool_kernel_size_;
}
inline void FasterRcnn::set_maxpool_kernel_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  maxpool_kernel_size_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.maxpool_kernel_size)
}

// optional int32 maxpool_stride = 20;
inline bool FasterRcnn::has_maxpool_stride() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void FasterRcnn::clear_maxpool_stride() {
  maxpool_stride_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::maxpool_stride() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.maxpool_stride)
  return maxpool_stride_;
}
inline void FasterRcnn::set_maxpool_stride(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00001000u;
  maxpool_stride_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.maxpool_stride)
}

// optional .object_detection.protos.BoxPredictor second_stage_box_predictor = 21;
inline bool FasterRcnn::has_second_stage_box_predictor() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline const ::object_detection::protos::BoxPredictor& FasterRcnn::second_stage_box_predictor() const {
  const ::object_detection::protos::BoxPredictor* p = second_stage_box_predictor_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_box_predictor)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::BoxPredictor*>(
      &::object_detection::protos::_BoxPredictor_default_instance_);
}
inline ::object_detection::protos::BoxPredictor* FasterRcnn::release_second_stage_box_predictor() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.second_stage_box_predictor)
  _has_bits_[0] &= ~0x00000010u;
  ::object_detection::protos::BoxPredictor* temp = second_stage_box_predictor_;
  second_stage_box_predictor_ = nullptr;
  return temp;
}
inline ::object_detection::protos::BoxPredictor* FasterRcnn::mutable_second_stage_box_predictor() {
  _has_bits_[0] |= 0x00000010u;
  if (second_stage_box_predictor_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::BoxPredictor>(GetArenaNoVirtual());
    second_stage_box_predictor_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.second_stage_box_predictor)
  return second_stage_box_predictor_;
}
inline void FasterRcnn::set_allocated_second_stage_box_predictor(::object_detection::protos::BoxPredictor* second_stage_box_predictor) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(second_stage_box_predictor_);
  }
  if (second_stage_box_predictor) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      second_stage_box_predictor = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, second_stage_box_predictor, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  second_stage_box_predictor_ = second_stage_box_predictor;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.second_stage_box_predictor)
}

// optional int32 second_stage_batch_size = 22 [default = 64];
inline bool FasterRcnn::has_second_stage_batch_size() const {
  return (_has_bits_[0] & 0x40000000u) != 0;
}
inline void FasterRcnn::clear_second_stage_batch_size() {
  second_stage_batch_size_ = 64;
  _has_bits_[0] &= ~0x40000000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnn::second_stage_batch_size() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_batch_size)
  return second_stage_batch_size_;
}
inline void FasterRcnn::set_second_stage_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x40000000u;
  second_stage_batch_size_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.second_stage_batch_size)
}

// optional float second_stage_balance_fraction = 23 [default = 0.25];
inline bool FasterRcnn::has_second_stage_balance_fraction() const {
  return (_has_bits_[0] & 0x80000000u) != 0;
}
inline void FasterRcnn::clear_second_stage_balance_fraction() {
  second_stage_balance_fraction_ = 0.25f;
  _has_bits_[0] &= ~0x80000000u;
}
inline float FasterRcnn::second_stage_balance_fraction() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_balance_fraction)
  return second_stage_balance_fraction_;
}
inline void FasterRcnn::set_second_stage_balance_fraction(float value) {
  _has_bits_[0] |= 0x80000000u;
  second_stage_balance_fraction_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.second_stage_balance_fraction)
}

// optional .object_detection.protos.PostProcessing second_stage_post_processing = 24;
inline bool FasterRcnn::has_second_stage_post_processing() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline const ::object_detection::protos::PostProcessing& FasterRcnn::second_stage_post_processing() const {
  const ::object_detection::protos::PostProcessing* p = second_stage_post_processing_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_post_processing)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::PostProcessing*>(
      &::object_detection::protos::_PostProcessing_default_instance_);
}
inline ::object_detection::protos::PostProcessing* FasterRcnn::release_second_stage_post_processing() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.second_stage_post_processing)
  _has_bits_[0] &= ~0x00000020u;
  ::object_detection::protos::PostProcessing* temp = second_stage_post_processing_;
  second_stage_post_processing_ = nullptr;
  return temp;
}
inline ::object_detection::protos::PostProcessing* FasterRcnn::mutable_second_stage_post_processing() {
  _has_bits_[0] |= 0x00000020u;
  if (second_stage_post_processing_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::PostProcessing>(GetArenaNoVirtual());
    second_stage_post_processing_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.second_stage_post_processing)
  return second_stage_post_processing_;
}
inline void FasterRcnn::set_allocated_second_stage_post_processing(::object_detection::protos::PostProcessing* second_stage_post_processing) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(second_stage_post_processing_);
  }
  if (second_stage_post_processing) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      second_stage_post_processing = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, second_stage_post_processing, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  second_stage_post_processing_ = second_stage_post_processing;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.second_stage_post_processing)
}

// optional float second_stage_localization_loss_weight = 25 [default = 1];
inline bool FasterRcnn::has_second_stage_localization_loss_weight() const {
  return (_has_bits_[1] & 0x00000001u) != 0;
}
inline void FasterRcnn::clear_second_stage_localization_loss_weight() {
  second_stage_localization_loss_weight_ = 1;
  _has_bits_[1] &= ~0x00000001u;
}
inline float FasterRcnn::second_stage_localization_loss_weight() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_localization_loss_weight)
  return second_stage_localization_loss_weight_;
}
inline void FasterRcnn::set_second_stage_localization_loss_weight(float value) {
  _has_bits_[1] |= 0x00000001u;
  second_stage_localization_loss_weight_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.second_stage_localization_loss_weight)
}

// optional float second_stage_classification_loss_weight = 26 [default = 1];
inline bool FasterRcnn::has_second_stage_classification_loss_weight() const {
  return (_has_bits_[1] & 0x00000002u) != 0;
}
inline void FasterRcnn::clear_second_stage_classification_loss_weight() {
  second_stage_classification_loss_weight_ = 1;
  _has_bits_[1] &= ~0x00000002u;
}
inline float FasterRcnn::second_stage_classification_loss_weight() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_classification_loss_weight)
  return second_stage_classification_loss_weight_;
}
inline void FasterRcnn::set_second_stage_classification_loss_weight(float value) {
  _has_bits_[1] |= 0x00000002u;
  second_stage_classification_loss_weight_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.second_stage_classification_loss_weight)
}

// optional float second_stage_mask_prediction_loss_weight = 27 [default = 1];
inline bool FasterRcnn::has_second_stage_mask_prediction_loss_weight() const {
  return (_has_bits_[1] & 0x00000004u) != 0;
}
inline void FasterRcnn::clear_second_stage_mask_prediction_loss_weight() {
  second_stage_mask_prediction_loss_weight_ = 1;
  _has_bits_[1] &= ~0x00000004u;
}
inline float FasterRcnn::second_stage_mask_prediction_loss_weight() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_mask_prediction_loss_weight)
  return second_stage_mask_prediction_loss_weight_;
}
inline void FasterRcnn::set_second_stage_mask_prediction_loss_weight(float value) {
  _has_bits_[1] |= 0x00000004u;
  second_stage_mask_prediction_loss_weight_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.second_stage_mask_prediction_loss_weight)
}

// optional .object_detection.protos.HardExampleMiner hard_example_miner = 28;
inline bool FasterRcnn::has_hard_example_miner() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline const ::object_detection::protos::HardExampleMiner& FasterRcnn::hard_example_miner() const {
  const ::object_detection::protos::HardExampleMiner* p = hard_example_miner_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.hard_example_miner)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::HardExampleMiner*>(
      &::object_detection::protos::_HardExampleMiner_default_instance_);
}
inline ::object_detection::protos::HardExampleMiner* FasterRcnn::release_hard_example_miner() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.hard_example_miner)
  _has_bits_[0] &= ~0x00000040u;
  ::object_detection::protos::HardExampleMiner* temp = hard_example_miner_;
  hard_example_miner_ = nullptr;
  return temp;
}
inline ::object_detection::protos::HardExampleMiner* FasterRcnn::mutable_hard_example_miner() {
  _has_bits_[0] |= 0x00000040u;
  if (hard_example_miner_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::HardExampleMiner>(GetArenaNoVirtual());
    hard_example_miner_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.hard_example_miner)
  return hard_example_miner_;
}
inline void FasterRcnn::set_allocated_hard_example_miner(::object_detection::protos::HardExampleMiner* hard_example_miner) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(hard_example_miner_);
  }
  if (hard_example_miner) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      hard_example_miner = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hard_example_miner, submessage_arena);
    }
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  hard_example_miner_ = hard_example_miner;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.hard_example_miner)
}

// optional .object_detection.protos.ClassificationLoss second_stage_classification_loss = 29;
inline bool FasterRcnn::has_second_stage_classification_loss() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline const ::object_detection::protos::ClassificationLoss& FasterRcnn::second_stage_classification_loss() const {
  const ::object_detection::protos::ClassificationLoss* p = second_stage_classification_loss_;
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.second_stage_classification_loss)
  return p != nullptr ? *p : *reinterpret_cast<const ::object_detection::protos::ClassificationLoss*>(
      &::object_detection::protos::_ClassificationLoss_default_instance_);
}
inline ::object_detection::protos::ClassificationLoss* FasterRcnn::release_second_stage_classification_loss() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnn.second_stage_classification_loss)
  _has_bits_[0] &= ~0x00000080u;
  ::object_detection::protos::ClassificationLoss* temp = second_stage_classification_loss_;
  second_stage_classification_loss_ = nullptr;
  return temp;
}
inline ::object_detection::protos::ClassificationLoss* FasterRcnn::mutable_second_stage_classification_loss() {
  _has_bits_[0] |= 0x00000080u;
  if (second_stage_classification_loss_ == nullptr) {
    auto* p = CreateMaybeMessage<::object_detection::protos::ClassificationLoss>(GetArenaNoVirtual());
    second_stage_classification_loss_ = p;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnn.second_stage_classification_loss)
  return second_stage_classification_loss_;
}
inline void FasterRcnn::set_allocated_second_stage_classification_loss(::object_detection::protos::ClassificationLoss* second_stage_classification_loss) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(second_stage_classification_loss_);
  }
  if (second_stage_classification_loss) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      second_stage_classification_loss = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, second_stage_classification_loss, submessage_arena);
    }
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  second_stage_classification_loss_ = second_stage_classification_loss;
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnn.second_stage_classification_loss)
}

// optional bool inplace_batchnorm_update = 30 [default = false];
inline bool FasterRcnn::has_inplace_batchnorm_update() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void FasterRcnn::clear_inplace_batchnorm_update() {
  inplace_batchnorm_update_ = false;
  _has_bits_[0] &= ~0x00002000u;
}
inline bool FasterRcnn::inplace_batchnorm_update() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.inplace_batchnorm_update)
  return inplace_batchnorm_update_;
}
inline void FasterRcnn::set_inplace_batchnorm_update(bool value) {
  _has_bits_[0] |= 0x00002000u;
  inplace_batchnorm_update_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.inplace_batchnorm_update)
}

// optional bool use_matmul_crop_and_resize = 31 [default = false];
inline bool FasterRcnn::has_use_matmul_crop_and_resize() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void FasterRcnn::clear_use_matmul_crop_and_resize() {
  use_matmul_crop_and_resize_ = false;
  _has_bits_[0] &= ~0x00004000u;
}
inline bool FasterRcnn::use_matmul_crop_and_resize() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.use_matmul_crop_and_resize)
  return use_matmul_crop_and_resize_;
}
inline void FasterRcnn::set_use_matmul_crop_and_resize(bool value) {
  _has_bits_[0] |= 0x00004000u;
  use_matmul_crop_and_resize_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.use_matmul_crop_and_resize)
}

// optional bool clip_anchors_to_image = 32 [default = false];
inline bool FasterRcnn::has_clip_anchors_to_image() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void FasterRcnn::clear_clip_anchors_to_image() {
  clip_anchors_to_image_ = false;
  _has_bits_[0] &= ~0x00008000u;
}
inline bool FasterRcnn::clip_anchors_to_image() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.clip_anchors_to_image)
  return clip_anchors_to_image_;
}
inline void FasterRcnn::set_clip_anchors_to_image(bool value) {
  _has_bits_[0] |= 0x00008000u;
  clip_anchors_to_image_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.clip_anchors_to_image)
}

// optional bool use_matmul_gather_in_matcher = 33 [default = false];
inline bool FasterRcnn::has_use_matmul_gather_in_matcher() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void FasterRcnn::clear_use_matmul_gather_in_matcher() {
  use_matmul_gather_in_matcher_ = false;
  _has_bits_[0] &= ~0x00010000u;
}
inline bool FasterRcnn::use_matmul_gather_in_matcher() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.use_matmul_gather_in_matcher)
  return use_matmul_gather_in_matcher_;
}
inline void FasterRcnn::set_use_matmul_gather_in_matcher(bool value) {
  _has_bits_[0] |= 0x00010000u;
  use_matmul_gather_in_matcher_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.use_matmul_gather_in_matcher)
}

// optional bool use_static_balanced_label_sampler = 34 [default = false];
inline bool FasterRcnn::has_use_static_balanced_label_sampler() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void FasterRcnn::clear_use_static_balanced_label_sampler() {
  use_static_balanced_label_sampler_ = false;
  _has_bits_[0] &= ~0x00020000u;
}
inline bool FasterRcnn::use_static_balanced_label_sampler() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.use_static_balanced_label_sampler)
  return use_static_balanced_label_sampler_;
}
inline void FasterRcnn::set_use_static_balanced_label_sampler(bool value) {
  _has_bits_[0] |= 0x00020000u;
  use_static_balanced_label_sampler_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.use_static_balanced_label_sampler)
}

// optional bool use_static_shapes = 35 [default = false];
inline bool FasterRcnn::has_use_static_shapes() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void FasterRcnn::clear_use_static_shapes() {
  use_static_shapes_ = false;
  _has_bits_[0] &= ~0x00040000u;
}
inline bool FasterRcnn::use_static_shapes() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.use_static_shapes)
  return use_static_shapes_;
}
inline void FasterRcnn::set_use_static_shapes(bool value) {
  _has_bits_[0] |= 0x00040000u;
  use_static_shapes_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.use_static_shapes)
}

// optional bool resize_masks = 36 [default = true];
inline bool FasterRcnn::has_resize_masks() const {
  return (_has_bits_[1] & 0x00000008u) != 0;
}
inline void FasterRcnn::clear_resize_masks() {
  resize_masks_ = true;
  _has_bits_[1] &= ~0x00000008u;
}
inline bool FasterRcnn::resize_masks() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.resize_masks)
  return resize_masks_;
}
inline void FasterRcnn::set_resize_masks(bool value) {
  _has_bits_[1] |= 0x00000008u;
  resize_masks_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.resize_masks)
}

// optional bool use_static_shapes_for_eval = 37 [default = false];
inline bool FasterRcnn::has_use_static_shapes_for_eval() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void FasterRcnn::clear_use_static_shapes_for_eval() {
  use_static_shapes_for_eval_ = false;
  _has_bits_[0] &= ~0x00080000u;
}
inline bool FasterRcnn::use_static_shapes_for_eval() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnn.use_static_shapes_for_eval)
  return use_static_shapes_for_eval_;
}
inline void FasterRcnn::set_use_static_shapes_for_eval(bool value) {
  _has_bits_[0] |= 0x00080000u;
  use_static_shapes_for_eval_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnn.use_static_shapes_for_eval)
}

// -------------------------------------------------------------------

// FasterRcnnFeatureExtractor

// optional string type = 1;
inline bool FasterRcnnFeatureExtractor::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FasterRcnnFeatureExtractor::clear_type() {
  type_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FasterRcnnFeatureExtractor::type() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnnFeatureExtractor.type)
  return type_.GetNoArena();
}
inline void FasterRcnnFeatureExtractor::set_type(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnnFeatureExtractor.type)
}
inline void FasterRcnnFeatureExtractor::set_type(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  type_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:object_detection.protos.FasterRcnnFeatureExtractor.type)
}
inline void FasterRcnnFeatureExtractor::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:object_detection.protos.FasterRcnnFeatureExtractor.type)
}
inline void FasterRcnnFeatureExtractor::set_type(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:object_detection.protos.FasterRcnnFeatureExtractor.type)
}
inline std::string* FasterRcnnFeatureExtractor::mutable_type() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:object_detection.protos.FasterRcnnFeatureExtractor.type)
  return type_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* FasterRcnnFeatureExtractor::release_type() {
  // @@protoc_insertion_point(field_release:object_detection.protos.FasterRcnnFeatureExtractor.type)
  if (!has_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return type_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void FasterRcnnFeatureExtractor::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  type_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:object_detection.protos.FasterRcnnFeatureExtractor.type)
}

// optional int32 first_stage_features_stride = 2 [default = 16];
inline bool FasterRcnnFeatureExtractor::has_first_stage_features_stride() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FasterRcnnFeatureExtractor::clear_first_stage_features_stride() {
  first_stage_features_stride_ = 16;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FasterRcnnFeatureExtractor::first_stage_features_stride() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnnFeatureExtractor.first_stage_features_stride)
  return first_stage_features_stride_;
}
inline void FasterRcnnFeatureExtractor::set_first_stage_features_stride(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  first_stage_features_stride_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnnFeatureExtractor.first_stage_features_stride)
}

// optional bool batch_norm_trainable = 3 [default = false];
inline bool FasterRcnnFeatureExtractor::has_batch_norm_trainable() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FasterRcnnFeatureExtractor::clear_batch_norm_trainable() {
  batch_norm_trainable_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool FasterRcnnFeatureExtractor::batch_norm_trainable() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.FasterRcnnFeatureExtractor.batch_norm_trainable)
  return batch_norm_trainable_;
}
inline void FasterRcnnFeatureExtractor::set_batch_norm_trainable(bool value) {
  _has_bits_[0] |= 0x00000002u;
  batch_norm_trainable_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.FasterRcnnFeatureExtractor.batch_norm_trainable)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace object_detection

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2ffaster_5frcnn_2eproto
