// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/region_similarity_calculator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
namespace object_detection {
namespace protos {
class IoaSimilarity;
class IoaSimilarityDefaultTypeInternal;
extern IoaSimilarityDefaultTypeInternal _IoaSimilarity_default_instance_;
class IouSimilarity;
class IouSimilarityDefaultTypeInternal;
extern IouSimilarityDefaultTypeInternal _IouSimilarity_default_instance_;
class NegSqDistSimilarity;
class NegSqDistSimilarityDefaultTypeInternal;
extern NegSqDistSimilarityDefaultTypeInternal _NegSqDistSimilarity_default_instance_;
class RegionSimilarityCalculator;
class RegionSimilarityCalculatorDefaultTypeInternal;
extern RegionSimilarityCalculatorDefaultTypeInternal _RegionSimilarityCalculator_default_instance_;
class ThresholdedIouSimilarity;
class ThresholdedIouSimilarityDefaultTypeInternal;
extern ThresholdedIouSimilarityDefaultTypeInternal _ThresholdedIouSimilarity_default_instance_;
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> ::object_detection::protos::IoaSimilarity* Arena::CreateMaybeMessage<::object_detection::protos::IoaSimilarity>(Arena*);
template<> ::object_detection::protos::IouSimilarity* Arena::CreateMaybeMessage<::object_detection::protos::IouSimilarity>(Arena*);
template<> ::object_detection::protos::NegSqDistSimilarity* Arena::CreateMaybeMessage<::object_detection::protos::NegSqDistSimilarity>(Arena*);
template<> ::object_detection::protos::RegionSimilarityCalculator* Arena::CreateMaybeMessage<::object_detection::protos::RegionSimilarityCalculator>(Arena*);
template<> ::object_detection::protos::ThresholdedIouSimilarity* Arena::CreateMaybeMessage<::object_detection::protos::ThresholdedIouSimilarity>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace object_detection {
namespace protos {

// ===================================================================

class RegionSimilarityCalculator :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.RegionSimilarityCalculator) */ {
 public:
  RegionSimilarityCalculator();
  virtual ~RegionSimilarityCalculator();

  RegionSimilarityCalculator(const RegionSimilarityCalculator& from);
  RegionSimilarityCalculator(RegionSimilarityCalculator&& from) noexcept
    : RegionSimilarityCalculator() {
    *this = ::std::move(from);
  }

  inline RegionSimilarityCalculator& operator=(const RegionSimilarityCalculator& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegionSimilarityCalculator& operator=(RegionSimilarityCalculator&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegionSimilarityCalculator& default_instance();

  enum RegionSimilarityCase {
    kNegSqDistSimilarity = 1,
    kIouSimilarity = 2,
    kIoaSimilarity = 3,
    kThresholdedIouSimilarity = 4,
    REGION_SIMILARITY_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegionSimilarityCalculator* internal_default_instance() {
    return reinterpret_cast<const RegionSimilarityCalculator*>(
               &_RegionSimilarityCalculator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegionSimilarityCalculator& a, RegionSimilarityCalculator& b) {
    a.Swap(&b);
  }
  inline void Swap(RegionSimilarityCalculator* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegionSimilarityCalculator* New() const final {
    return CreateMaybeMessage<RegionSimilarityCalculator>(nullptr);
  }

  RegionSimilarityCalculator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegionSimilarityCalculator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegionSimilarityCalculator& from);
  void MergeFrom(const RegionSimilarityCalculator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegionSimilarityCalculator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.RegionSimilarityCalculator";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNegSqDistSimilarityFieldNumber = 1,
    kIouSimilarityFieldNumber = 2,
    kIoaSimilarityFieldNumber = 3,
    kThresholdedIouSimilarityFieldNumber = 4,
  };
  // optional .object_detection.protos.NegSqDistSimilarity neg_sq_dist_similarity = 1;
  bool has_neg_sq_dist_similarity() const;
  void clear_neg_sq_dist_similarity();
  const ::object_detection::protos::NegSqDistSimilarity& neg_sq_dist_similarity() const;
  ::object_detection::protos::NegSqDistSimilarity* release_neg_sq_dist_similarity();
  ::object_detection::protos::NegSqDistSimilarity* mutable_neg_sq_dist_similarity();
  void set_allocated_neg_sq_dist_similarity(::object_detection::protos::NegSqDistSimilarity* neg_sq_dist_similarity);

  // optional .object_detection.protos.IouSimilarity iou_similarity = 2;
  bool has_iou_similarity() const;
  void clear_iou_similarity();
  const ::object_detection::protos::IouSimilarity& iou_similarity() const;
  ::object_detection::protos::IouSimilarity* release_iou_similarity();
  ::object_detection::protos::IouSimilarity* mutable_iou_similarity();
  void set_allocated_iou_similarity(::object_detection::protos::IouSimilarity* iou_similarity);

  // optional .object_detection.protos.IoaSimilarity ioa_similarity = 3;
  bool has_ioa_similarity() const;
  void clear_ioa_similarity();
  const ::object_detection::protos::IoaSimilarity& ioa_similarity() const;
  ::object_detection::protos::IoaSimilarity* release_ioa_similarity();
  ::object_detection::protos::IoaSimilarity* mutable_ioa_similarity();
  void set_allocated_ioa_similarity(::object_detection::protos::IoaSimilarity* ioa_similarity);

  // optional .object_detection.protos.ThresholdedIouSimilarity thresholded_iou_similarity = 4;
  bool has_thresholded_iou_similarity() const;
  void clear_thresholded_iou_similarity();
  const ::object_detection::protos::ThresholdedIouSimilarity& thresholded_iou_similarity() const;
  ::object_detection::protos::ThresholdedIouSimilarity* release_thresholded_iou_similarity();
  ::object_detection::protos::ThresholdedIouSimilarity* mutable_thresholded_iou_similarity();
  void set_allocated_thresholded_iou_similarity(::object_detection::protos::ThresholdedIouSimilarity* thresholded_iou_similarity);

  void clear_region_similarity();
  RegionSimilarityCase region_similarity_case() const;
  // @@protoc_insertion_point(class_scope:object_detection.protos.RegionSimilarityCalculator)
 private:
  class _Internal;
  void set_has_neg_sq_dist_similarity();
  void set_has_iou_similarity();
  void set_has_ioa_similarity();
  void set_has_thresholded_iou_similarity();

  inline bool has_region_similarity() const;
  inline void clear_has_region_similarity();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  union RegionSimilarityUnion {
    RegionSimilarityUnion() {}
    ::object_detection::protos::NegSqDistSimilarity* neg_sq_dist_similarity_;
    ::object_detection::protos::IouSimilarity* iou_similarity_;
    ::object_detection::protos::IoaSimilarity* ioa_similarity_;
    ::object_detection::protos::ThresholdedIouSimilarity* thresholded_iou_similarity_;
  } region_similarity_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class NegSqDistSimilarity :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.NegSqDistSimilarity) */ {
 public:
  NegSqDistSimilarity();
  virtual ~NegSqDistSimilarity();

  NegSqDistSimilarity(const NegSqDistSimilarity& from);
  NegSqDistSimilarity(NegSqDistSimilarity&& from) noexcept
    : NegSqDistSimilarity() {
    *this = ::std::move(from);
  }

  inline NegSqDistSimilarity& operator=(const NegSqDistSimilarity& from) {
    CopyFrom(from);
    return *this;
  }
  inline NegSqDistSimilarity& operator=(NegSqDistSimilarity&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NegSqDistSimilarity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NegSqDistSimilarity* internal_default_instance() {
    return reinterpret_cast<const NegSqDistSimilarity*>(
               &_NegSqDistSimilarity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NegSqDistSimilarity& a, NegSqDistSimilarity& b) {
    a.Swap(&b);
  }
  inline void Swap(NegSqDistSimilarity* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NegSqDistSimilarity* New() const final {
    return CreateMaybeMessage<NegSqDistSimilarity>(nullptr);
  }

  NegSqDistSimilarity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NegSqDistSimilarity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NegSqDistSimilarity& from);
  void MergeFrom(const NegSqDistSimilarity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NegSqDistSimilarity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.NegSqDistSimilarity";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:object_detection.protos.NegSqDistSimilarity)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class IouSimilarity :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.IouSimilarity) */ {
 public:
  IouSimilarity();
  virtual ~IouSimilarity();

  IouSimilarity(const IouSimilarity& from);
  IouSimilarity(IouSimilarity&& from) noexcept
    : IouSimilarity() {
    *this = ::std::move(from);
  }

  inline IouSimilarity& operator=(const IouSimilarity& from) {
    CopyFrom(from);
    return *this;
  }
  inline IouSimilarity& operator=(IouSimilarity&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IouSimilarity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IouSimilarity* internal_default_instance() {
    return reinterpret_cast<const IouSimilarity*>(
               &_IouSimilarity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IouSimilarity& a, IouSimilarity& b) {
    a.Swap(&b);
  }
  inline void Swap(IouSimilarity* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IouSimilarity* New() const final {
    return CreateMaybeMessage<IouSimilarity>(nullptr);
  }

  IouSimilarity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IouSimilarity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IouSimilarity& from);
  void MergeFrom(const IouSimilarity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IouSimilarity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.IouSimilarity";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:object_detection.protos.IouSimilarity)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class IoaSimilarity :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.IoaSimilarity) */ {
 public:
  IoaSimilarity();
  virtual ~IoaSimilarity();

  IoaSimilarity(const IoaSimilarity& from);
  IoaSimilarity(IoaSimilarity&& from) noexcept
    : IoaSimilarity() {
    *this = ::std::move(from);
  }

  inline IoaSimilarity& operator=(const IoaSimilarity& from) {
    CopyFrom(from);
    return *this;
  }
  inline IoaSimilarity& operator=(IoaSimilarity&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IoaSimilarity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IoaSimilarity* internal_default_instance() {
    return reinterpret_cast<const IoaSimilarity*>(
               &_IoaSimilarity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(IoaSimilarity& a, IoaSimilarity& b) {
    a.Swap(&b);
  }
  inline void Swap(IoaSimilarity* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IoaSimilarity* New() const final {
    return CreateMaybeMessage<IoaSimilarity>(nullptr);
  }

  IoaSimilarity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IoaSimilarity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IoaSimilarity& from);
  void MergeFrom(const IoaSimilarity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IoaSimilarity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.IoaSimilarity";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:object_detection.protos.IoaSimilarity)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class ThresholdedIouSimilarity :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.ThresholdedIouSimilarity) */ {
 public:
  ThresholdedIouSimilarity();
  virtual ~ThresholdedIouSimilarity();

  ThresholdedIouSimilarity(const ThresholdedIouSimilarity& from);
  ThresholdedIouSimilarity(ThresholdedIouSimilarity&& from) noexcept
    : ThresholdedIouSimilarity() {
    *this = ::std::move(from);
  }

  inline ThresholdedIouSimilarity& operator=(const ThresholdedIouSimilarity& from) {
    CopyFrom(from);
    return *this;
  }
  inline ThresholdedIouSimilarity& operator=(ThresholdedIouSimilarity&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ThresholdedIouSimilarity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ThresholdedIouSimilarity* internal_default_instance() {
    return reinterpret_cast<const ThresholdedIouSimilarity*>(
               &_ThresholdedIouSimilarity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ThresholdedIouSimilarity& a, ThresholdedIouSimilarity& b) {
    a.Swap(&b);
  }
  inline void Swap(ThresholdedIouSimilarity* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ThresholdedIouSimilarity* New() const final {
    return CreateMaybeMessage<ThresholdedIouSimilarity>(nullptr);
  }

  ThresholdedIouSimilarity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ThresholdedIouSimilarity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ThresholdedIouSimilarity& from);
  void MergeFrom(const ThresholdedIouSimilarity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ThresholdedIouSimilarity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.ThresholdedIouSimilarity";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIouThresholdFieldNumber = 1,
  };
  // optional float iou_threshold = 1 [default = 0.5];
  bool has_iou_threshold() const;
  void clear_iou_threshold();
  float iou_threshold() const;
  void set_iou_threshold(float value);

  // @@protoc_insertion_point(class_scope:object_detection.protos.ThresholdedIouSimilarity)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float iou_threshold_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegionSimilarityCalculator

// optional .object_detection.protos.NegSqDistSimilarity neg_sq_dist_similarity = 1;
inline bool RegionSimilarityCalculator::has_neg_sq_dist_similarity() const {
  return region_similarity_case() == kNegSqDistSimilarity;
}
inline void RegionSimilarityCalculator::set_has_neg_sq_dist_similarity() {
  _oneof_case_[0] = kNegSqDistSimilarity;
}
inline void RegionSimilarityCalculator::clear_neg_sq_dist_similarity() {
  if (has_neg_sq_dist_similarity()) {
    delete region_similarity_.neg_sq_dist_similarity_;
    clear_has_region_similarity();
  }
}
inline ::object_detection::protos::NegSqDistSimilarity* RegionSimilarityCalculator::release_neg_sq_dist_similarity() {
  // @@protoc_insertion_point(field_release:object_detection.protos.RegionSimilarityCalculator.neg_sq_dist_similarity)
  if (has_neg_sq_dist_similarity()) {
    clear_has_region_similarity();
      ::object_detection::protos::NegSqDistSimilarity* temp = region_similarity_.neg_sq_dist_similarity_;
    region_similarity_.neg_sq_dist_similarity_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::object_detection::protos::NegSqDistSimilarity& RegionSimilarityCalculator::neg_sq_dist_similarity() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.RegionSimilarityCalculator.neg_sq_dist_similarity)
  return has_neg_sq_dist_similarity()
      ? *region_similarity_.neg_sq_dist_similarity_
      : *reinterpret_cast< ::object_detection::protos::NegSqDistSimilarity*>(&::object_detection::protos::_NegSqDistSimilarity_default_instance_);
}
inline ::object_detection::protos::NegSqDistSimilarity* RegionSimilarityCalculator::mutable_neg_sq_dist_similarity() {
  if (!has_neg_sq_dist_similarity()) {
    clear_region_similarity();
    set_has_neg_sq_dist_similarity();
    region_similarity_.neg_sq_dist_similarity_ = CreateMaybeMessage< ::object_detection::protos::NegSqDistSimilarity >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.RegionSimilarityCalculator.neg_sq_dist_similarity)
  return region_similarity_.neg_sq_dist_similarity_;
}

// optional .object_detection.protos.IouSimilarity iou_similarity = 2;
inline bool RegionSimilarityCalculator::has_iou_similarity() const {
  return region_similarity_case() == kIouSimilarity;
}
inline void RegionSimilarityCalculator::set_has_iou_similarity() {
  _oneof_case_[0] = kIouSimilarity;
}
inline void RegionSimilarityCalculator::clear_iou_similarity() {
  if (has_iou_similarity()) {
    delete region_similarity_.iou_similarity_;
    clear_has_region_similarity();
  }
}
inline ::object_detection::protos::IouSimilarity* RegionSimilarityCalculator::release_iou_similarity() {
  // @@protoc_insertion_point(field_release:object_detection.protos.RegionSimilarityCalculator.iou_similarity)
  if (has_iou_similarity()) {
    clear_has_region_similarity();
      ::object_detection::protos::IouSimilarity* temp = region_similarity_.iou_similarity_;
    region_similarity_.iou_similarity_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::object_detection::protos::IouSimilarity& RegionSimilarityCalculator::iou_similarity() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.RegionSimilarityCalculator.iou_similarity)
  return has_iou_similarity()
      ? *region_similarity_.iou_similarity_
      : *reinterpret_cast< ::object_detection::protos::IouSimilarity*>(&::object_detection::protos::_IouSimilarity_default_instance_);
}
inline ::object_detection::protos::IouSimilarity* RegionSimilarityCalculator::mutable_iou_similarity() {
  if (!has_iou_similarity()) {
    clear_region_similarity();
    set_has_iou_similarity();
    region_similarity_.iou_similarity_ = CreateMaybeMessage< ::object_detection::protos::IouSimilarity >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.RegionSimilarityCalculator.iou_similarity)
  return region_similarity_.iou_similarity_;
}

// optional .object_detection.protos.IoaSimilarity ioa_similarity = 3;
inline bool RegionSimilarityCalculator::has_ioa_similarity() const {
  return region_similarity_case() == kIoaSimilarity;
}
inline void RegionSimilarityCalculator::set_has_ioa_similarity() {
  _oneof_case_[0] = kIoaSimilarity;
}
inline void RegionSimilarityCalculator::clear_ioa_similarity() {
  if (has_ioa_similarity()) {
    delete region_similarity_.ioa_similarity_;
    clear_has_region_similarity();
  }
}
inline ::object_detection::protos::IoaSimilarity* RegionSimilarityCalculator::release_ioa_similarity() {
  // @@protoc_insertion_point(field_release:object_detection.protos.RegionSimilarityCalculator.ioa_similarity)
  if (has_ioa_similarity()) {
    clear_has_region_similarity();
      ::object_detection::protos::IoaSimilarity* temp = region_similarity_.ioa_similarity_;
    region_similarity_.ioa_similarity_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::object_detection::protos::IoaSimilarity& RegionSimilarityCalculator::ioa_similarity() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.RegionSimilarityCalculator.ioa_similarity)
  return has_ioa_similarity()
      ? *region_similarity_.ioa_similarity_
      : *reinterpret_cast< ::object_detection::protos::IoaSimilarity*>(&::object_detection::protos::_IoaSimilarity_default_instance_);
}
inline ::object_detection::protos::IoaSimilarity* RegionSimilarityCalculator::mutable_ioa_similarity() {
  if (!has_ioa_similarity()) {
    clear_region_similarity();
    set_has_ioa_similarity();
    region_similarity_.ioa_similarity_ = CreateMaybeMessage< ::object_detection::protos::IoaSimilarity >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.RegionSimilarityCalculator.ioa_similarity)
  return region_similarity_.ioa_similarity_;
}

// optional .object_detection.protos.ThresholdedIouSimilarity thresholded_iou_similarity = 4;
inline bool RegionSimilarityCalculator::has_thresholded_iou_similarity() const {
  return region_similarity_case() == kThresholdedIouSimilarity;
}
inline void RegionSimilarityCalculator::set_has_thresholded_iou_similarity() {
  _oneof_case_[0] = kThresholdedIouSimilarity;
}
inline void RegionSimilarityCalculator::clear_thresholded_iou_similarity() {
  if (has_thresholded_iou_similarity()) {
    delete region_similarity_.thresholded_iou_similarity_;
    clear_has_region_similarity();
  }
}
inline ::object_detection::protos::ThresholdedIouSimilarity* RegionSimilarityCalculator::release_thresholded_iou_similarity() {
  // @@protoc_insertion_point(field_release:object_detection.protos.RegionSimilarityCalculator.thresholded_iou_similarity)
  if (has_thresholded_iou_similarity()) {
    clear_has_region_similarity();
      ::object_detection::protos::ThresholdedIouSimilarity* temp = region_similarity_.thresholded_iou_similarity_;
    region_similarity_.thresholded_iou_similarity_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::object_detection::protos::ThresholdedIouSimilarity& RegionSimilarityCalculator::thresholded_iou_similarity() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.RegionSimilarityCalculator.thresholded_iou_similarity)
  return has_thresholded_iou_similarity()
      ? *region_similarity_.thresholded_iou_similarity_
      : *reinterpret_cast< ::object_detection::protos::ThresholdedIouSimilarity*>(&::object_detection::protos::_ThresholdedIouSimilarity_default_instance_);
}
inline ::object_detection::protos::ThresholdedIouSimilarity* RegionSimilarityCalculator::mutable_thresholded_iou_similarity() {
  if (!has_thresholded_iou_similarity()) {
    clear_region_similarity();
    set_has_thresholded_iou_similarity();
    region_similarity_.thresholded_iou_similarity_ = CreateMaybeMessage< ::object_detection::protos::ThresholdedIouSimilarity >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:object_detection.protos.RegionSimilarityCalculator.thresholded_iou_similarity)
  return region_similarity_.thresholded_iou_similarity_;
}

inline bool RegionSimilarityCalculator::has_region_similarity() const {
  return region_similarity_case() != REGION_SIMILARITY_NOT_SET;
}
inline void RegionSimilarityCalculator::clear_has_region_similarity() {
  _oneof_case_[0] = REGION_SIMILARITY_NOT_SET;
}
inline RegionSimilarityCalculator::RegionSimilarityCase RegionSimilarityCalculator::region_similarity_case() const {
  return RegionSimilarityCalculator::RegionSimilarityCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// NegSqDistSimilarity

// -------------------------------------------------------------------

// IouSimilarity

// -------------------------------------------------------------------

// IoaSimilarity

// -------------------------------------------------------------------

// ThresholdedIouSimilarity

// optional float iou_threshold = 1 [default = 0.5];
inline bool ThresholdedIouSimilarity::has_iou_threshold() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ThresholdedIouSimilarity::clear_iou_threshold() {
  iou_threshold_ = 0.5f;
  _has_bits_[0] &= ~0x00000001u;
}
inline float ThresholdedIouSimilarity::iou_threshold() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.ThresholdedIouSimilarity.iou_threshold)
  return iou_threshold_;
}
inline void ThresholdedIouSimilarity::set_iou_threshold(float value) {
  _has_bits_[0] |= 0x00000001u;
  iou_threshold_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.ThresholdedIouSimilarity.iou_threshold)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace object_detection

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fregion_5fsimilarity_5fcalculator_2eproto
