// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/ssd_anchor_generator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto;
namespace object_detection {
namespace protos {
class SsdAnchorGenerator;
class SsdAnchorGeneratorDefaultTypeInternal;
extern SsdAnchorGeneratorDefaultTypeInternal _SsdAnchorGenerator_default_instance_;
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> ::object_detection::protos::SsdAnchorGenerator* Arena::CreateMaybeMessage<::object_detection::protos::SsdAnchorGenerator>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace object_detection {
namespace protos {

// ===================================================================

class SsdAnchorGenerator :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.SsdAnchorGenerator) */ {
 public:
  SsdAnchorGenerator();
  virtual ~SsdAnchorGenerator();

  SsdAnchorGenerator(const SsdAnchorGenerator& from);
  SsdAnchorGenerator(SsdAnchorGenerator&& from) noexcept
    : SsdAnchorGenerator() {
    *this = ::std::move(from);
  }

  inline SsdAnchorGenerator& operator=(const SsdAnchorGenerator& from) {
    CopyFrom(from);
    return *this;
  }
  inline SsdAnchorGenerator& operator=(SsdAnchorGenerator&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SsdAnchorGenerator& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SsdAnchorGenerator* internal_default_instance() {
    return reinterpret_cast<const SsdAnchorGenerator*>(
               &_SsdAnchorGenerator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SsdAnchorGenerator& a, SsdAnchorGenerator& b) {
    a.Swap(&b);
  }
  inline void Swap(SsdAnchorGenerator* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SsdAnchorGenerator* New() const final {
    return CreateMaybeMessage<SsdAnchorGenerator>(nullptr);
  }

  SsdAnchorGenerator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SsdAnchorGenerator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SsdAnchorGenerator& from);
  void MergeFrom(const SsdAnchorGenerator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SsdAnchorGenerator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.SsdAnchorGenerator";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto);
    return ::descriptor_table_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAspectRatiosFieldNumber = 4,
    kHeightStrideFieldNumber = 8,
    kWidthStrideFieldNumber = 9,
    kHeightOffsetFieldNumber = 10,
    kWidthOffsetFieldNumber = 11,
    kScalesFieldNumber = 12,
    kInterpolatedScaleAspectRatioFieldNumber = 13,
    kNumLayersFieldNumber = 1,
    kMinScaleFieldNumber = 2,
    kMaxScaleFieldNumber = 3,
    kReduceBoxesInLowestLayerFieldNumber = 5,
    kBaseAnchorHeightFieldNumber = 6,
    kBaseAnchorWidthFieldNumber = 7,
  };
  // repeated float aspect_ratios = 4;
  int aspect_ratios_size() const;
  void clear_aspect_ratios();
  float aspect_ratios(int index) const;
  void set_aspect_ratios(int index, float value);
  void add_aspect_ratios(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      aspect_ratios() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_aspect_ratios();

  // repeated int32 height_stride = 8;
  int height_stride_size() const;
  void clear_height_stride();
  ::PROTOBUF_NAMESPACE_ID::int32 height_stride(int index) const;
  void set_height_stride(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_height_stride(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      height_stride() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_height_stride();

  // repeated int32 width_stride = 9;
  int width_stride_size() const;
  void clear_width_stride();
  ::PROTOBUF_NAMESPACE_ID::int32 width_stride(int index) const;
  void set_width_stride(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_width_stride(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      width_stride() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_width_stride();

  // repeated int32 height_offset = 10;
  int height_offset_size() const;
  void clear_height_offset();
  ::PROTOBUF_NAMESPACE_ID::int32 height_offset(int index) const;
  void set_height_offset(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_height_offset(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      height_offset() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_height_offset();

  // repeated int32 width_offset = 11;
  int width_offset_size() const;
  void clear_width_offset();
  ::PROTOBUF_NAMESPACE_ID::int32 width_offset(int index) const;
  void set_width_offset(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_width_offset(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      width_offset() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_width_offset();

  // repeated float scales = 12;
  int scales_size() const;
  void clear_scales();
  float scales(int index) const;
  void set_scales(int index, float value);
  void add_scales(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      scales() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_scales();

  // optional float interpolated_scale_aspect_ratio = 13 [default = 1];
  bool has_interpolated_scale_aspect_ratio() const;
  void clear_interpolated_scale_aspect_ratio();
  float interpolated_scale_aspect_ratio() const;
  void set_interpolated_scale_aspect_ratio(float value);

  // optional int32 num_layers = 1 [default = 6];
  bool has_num_layers() const;
  void clear_num_layers();
  ::PROTOBUF_NAMESPACE_ID::int32 num_layers() const;
  void set_num_layers(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float min_scale = 2 [default = 0.2];
  bool has_min_scale() const;
  void clear_min_scale();
  float min_scale() const;
  void set_min_scale(float value);

  // optional float max_scale = 3 [default = 0.95];
  bool has_max_scale() const;
  void clear_max_scale();
  float max_scale() const;
  void set_max_scale(float value);

  // optional bool reduce_boxes_in_lowest_layer = 5 [default = true];
  bool has_reduce_boxes_in_lowest_layer() const;
  void clear_reduce_boxes_in_lowest_layer();
  bool reduce_boxes_in_lowest_layer() const;
  void set_reduce_boxes_in_lowest_layer(bool value);

  // optional float base_anchor_height = 6 [default = 1];
  bool has_base_anchor_height() const;
  void clear_base_anchor_height();
  float base_anchor_height() const;
  void set_base_anchor_height(float value);

  // optional float base_anchor_width = 7 [default = 1];
  bool has_base_anchor_width() const;
  void clear_base_anchor_width();
  float base_anchor_width() const;
  void set_base_anchor_width(float value);

  // @@protoc_insertion_point(class_scope:object_detection.protos.SsdAnchorGenerator)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > aspect_ratios_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > height_stride_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > width_stride_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > height_offset_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > width_offset_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > scales_;
  float interpolated_scale_aspect_ratio_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_layers_;
  float min_scale_;
  float max_scale_;
  bool reduce_boxes_in_lowest_layer_;
  float base_anchor_height_;
  float base_anchor_width_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SsdAnchorGenerator

// optional int32 num_layers = 1 [default = 6];
inline bool SsdAnchorGenerator::has_num_layers() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SsdAnchorGenerator::clear_num_layers() {
  num_layers_ = 6;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SsdAnchorGenerator::num_layers() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.num_layers)
  return num_layers_;
}
inline void SsdAnchorGenerator::set_num_layers(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  num_layers_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.num_layers)
}

// optional float min_scale = 2 [default = 0.2];
inline bool SsdAnchorGenerator::has_min_scale() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SsdAnchorGenerator::clear_min_scale() {
  min_scale_ = 0.2f;
  _has_bits_[0] &= ~0x00000004u;
}
inline float SsdAnchorGenerator::min_scale() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.min_scale)
  return min_scale_;
}
inline void SsdAnchorGenerator::set_min_scale(float value) {
  _has_bits_[0] |= 0x00000004u;
  min_scale_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.min_scale)
}

// optional float max_scale = 3 [default = 0.95];
inline bool SsdAnchorGenerator::has_max_scale() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SsdAnchorGenerator::clear_max_scale() {
  max_scale_ = 0.95f;
  _has_bits_[0] &= ~0x00000008u;
}
inline float SsdAnchorGenerator::max_scale() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.max_scale)
  return max_scale_;
}
inline void SsdAnchorGenerator::set_max_scale(float value) {
  _has_bits_[0] |= 0x00000008u;
  max_scale_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.max_scale)
}

// repeated float scales = 12;
inline int SsdAnchorGenerator::scales_size() const {
  return scales_.size();
}
inline void SsdAnchorGenerator::clear_scales() {
  scales_.Clear();
}
inline float SsdAnchorGenerator::scales(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.scales)
  return scales_.Get(index);
}
inline void SsdAnchorGenerator::set_scales(int index, float value) {
  scales_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.scales)
}
inline void SsdAnchorGenerator::add_scales(float value) {
  scales_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.scales)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
SsdAnchorGenerator::scales() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.scales)
  return scales_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
SsdAnchorGenerator::mutable_scales() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.scales)
  return &scales_;
}

// repeated float aspect_ratios = 4;
inline int SsdAnchorGenerator::aspect_ratios_size() const {
  return aspect_ratios_.size();
}
inline void SsdAnchorGenerator::clear_aspect_ratios() {
  aspect_ratios_.Clear();
}
inline float SsdAnchorGenerator::aspect_ratios(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.aspect_ratios)
  return aspect_ratios_.Get(index);
}
inline void SsdAnchorGenerator::set_aspect_ratios(int index, float value) {
  aspect_ratios_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.aspect_ratios)
}
inline void SsdAnchorGenerator::add_aspect_ratios(float value) {
  aspect_ratios_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.aspect_ratios)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
SsdAnchorGenerator::aspect_ratios() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.aspect_ratios)
  return aspect_ratios_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
SsdAnchorGenerator::mutable_aspect_ratios() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.aspect_ratios)
  return &aspect_ratios_;
}

// optional float interpolated_scale_aspect_ratio = 13 [default = 1];
inline bool SsdAnchorGenerator::has_interpolated_scale_aspect_ratio() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SsdAnchorGenerator::clear_interpolated_scale_aspect_ratio() {
  interpolated_scale_aspect_ratio_ = 1;
  _has_bits_[0] &= ~0x00000001u;
}
inline float SsdAnchorGenerator::interpolated_scale_aspect_ratio() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.interpolated_scale_aspect_ratio)
  return interpolated_scale_aspect_ratio_;
}
inline void SsdAnchorGenerator::set_interpolated_scale_aspect_ratio(float value) {
  _has_bits_[0] |= 0x00000001u;
  interpolated_scale_aspect_ratio_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.interpolated_scale_aspect_ratio)
}

// optional bool reduce_boxes_in_lowest_layer = 5 [default = true];
inline bool SsdAnchorGenerator::has_reduce_boxes_in_lowest_layer() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SsdAnchorGenerator::clear_reduce_boxes_in_lowest_layer() {
  reduce_boxes_in_lowest_layer_ = true;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool SsdAnchorGenerator::reduce_boxes_in_lowest_layer() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.reduce_boxes_in_lowest_layer)
  return reduce_boxes_in_lowest_layer_;
}
inline void SsdAnchorGenerator::set_reduce_boxes_in_lowest_layer(bool value) {
  _has_bits_[0] |= 0x00000010u;
  reduce_boxes_in_lowest_layer_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.reduce_boxes_in_lowest_layer)
}

// optional float base_anchor_height = 6 [default = 1];
inline bool SsdAnchorGenerator::has_base_anchor_height() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SsdAnchorGenerator::clear_base_anchor_height() {
  base_anchor_height_ = 1;
  _has_bits_[0] &= ~0x00000020u;
}
inline float SsdAnchorGenerator::base_anchor_height() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.base_anchor_height)
  return base_anchor_height_;
}
inline void SsdAnchorGenerator::set_base_anchor_height(float value) {
  _has_bits_[0] |= 0x00000020u;
  base_anchor_height_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.base_anchor_height)
}

// optional float base_anchor_width = 7 [default = 1];
inline bool SsdAnchorGenerator::has_base_anchor_width() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SsdAnchorGenerator::clear_base_anchor_width() {
  base_anchor_width_ = 1;
  _has_bits_[0] &= ~0x00000040u;
}
inline float SsdAnchorGenerator::base_anchor_width() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.base_anchor_width)
  return base_anchor_width_;
}
inline void SsdAnchorGenerator::set_base_anchor_width(float value) {
  _has_bits_[0] |= 0x00000040u;
  base_anchor_width_ = value;
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.base_anchor_width)
}

// repeated int32 height_stride = 8;
inline int SsdAnchorGenerator::height_stride_size() const {
  return height_stride_.size();
}
inline void SsdAnchorGenerator::clear_height_stride() {
  height_stride_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SsdAnchorGenerator::height_stride(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.height_stride)
  return height_stride_.Get(index);
}
inline void SsdAnchorGenerator::set_height_stride(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  height_stride_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.height_stride)
}
inline void SsdAnchorGenerator::add_height_stride(::PROTOBUF_NAMESPACE_ID::int32 value) {
  height_stride_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.height_stride)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
SsdAnchorGenerator::height_stride() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.height_stride)
  return height_stride_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
SsdAnchorGenerator::mutable_height_stride() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.height_stride)
  return &height_stride_;
}

// repeated int32 width_stride = 9;
inline int SsdAnchorGenerator::width_stride_size() const {
  return width_stride_.size();
}
inline void SsdAnchorGenerator::clear_width_stride() {
  width_stride_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SsdAnchorGenerator::width_stride(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.width_stride)
  return width_stride_.Get(index);
}
inline void SsdAnchorGenerator::set_width_stride(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  width_stride_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.width_stride)
}
inline void SsdAnchorGenerator::add_width_stride(::PROTOBUF_NAMESPACE_ID::int32 value) {
  width_stride_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.width_stride)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
SsdAnchorGenerator::width_stride() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.width_stride)
  return width_stride_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
SsdAnchorGenerator::mutable_width_stride() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.width_stride)
  return &width_stride_;
}

// repeated int32 height_offset = 10;
inline int SsdAnchorGenerator::height_offset_size() const {
  return height_offset_.size();
}
inline void SsdAnchorGenerator::clear_height_offset() {
  height_offset_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SsdAnchorGenerator::height_offset(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.height_offset)
  return height_offset_.Get(index);
}
inline void SsdAnchorGenerator::set_height_offset(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  height_offset_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.height_offset)
}
inline void SsdAnchorGenerator::add_height_offset(::PROTOBUF_NAMESPACE_ID::int32 value) {
  height_offset_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.height_offset)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
SsdAnchorGenerator::height_offset() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.height_offset)
  return height_offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
SsdAnchorGenerator::mutable_height_offset() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.height_offset)
  return &height_offset_;
}

// repeated int32 width_offset = 11;
inline int SsdAnchorGenerator::width_offset_size() const {
  return width_offset_.size();
}
inline void SsdAnchorGenerator::clear_width_offset() {
  width_offset_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SsdAnchorGenerator::width_offset(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SsdAnchorGenerator.width_offset)
  return width_offset_.Get(index);
}
inline void SsdAnchorGenerator::set_width_offset(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  width_offset_.Set(index, value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SsdAnchorGenerator.width_offset)
}
inline void SsdAnchorGenerator::add_width_offset(::PROTOBUF_NAMESPACE_ID::int32 value) {
  width_offset_.Add(value);
  // @@protoc_insertion_point(field_add:object_detection.protos.SsdAnchorGenerator.width_offset)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
SsdAnchorGenerator::width_offset() const {
  // @@protoc_insertion_point(field_list:object_detection.protos.SsdAnchorGenerator.width_offset)
  return width_offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
SsdAnchorGenerator::mutable_width_offset() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.protos.SsdAnchorGenerator.width_offset)
  return &width_offset_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace object_detection

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fssd_5fanchor_5fgenerator_2eproto
