#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 44
#define PANGO_VERSION_MICRO 6

#define PANGO_VERSION_STRING "1.44.6"

#endif /* PANGO_FEATURES_H */
